/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import HolographicMaterial from "./Helper/Hologram";

export function Ghost(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/ghost.glb");
  const { actions, names } = useAnimations(animations, group);
  
  useEffect(() => {
    actions[names[0]].reset().fadeIn(0.5).play()
  }, [])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='ghost' rotation={[Math.PI / 2, 0, 0]} scale={0.06}>
        <skinnedMesh name='Ch36' geometry={nodes.Ch36.geometry} skeleton={nodes.Ch36.skeleton}>
        <HolographicMaterial 
        fresnelAmount={0.75}
        fresnelOpacity={1}
        hologramBrightness={1.5}
        scanlineSize={1}
        signalSpeed={0}
        hologramColor={"#51a4de"}
        hologramOpacity={0.5}
        blinkFresnelOnly={false}
        enableBlinking={false}
        enableAdditive={false}
        side={"FrontSide"}
        />
        </skinnedMesh>
        <primitive object={nodes.mixamorig1Hips} />
      </group>
    </group>
  );
}

useGLTF.preload("/models/ghost.glb");
