/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Tree(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/tree.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" scale={[0.5,0.5,0.5]}>
        <group name="Tree">
          <group name="tree">
            <skinnedMesh
              name="tree_1"
              geometry={nodes.tree_1.geometry}
              material={materials.Leaf}
              skeleton={nodes.tree_1.skeleton}
            />
            <skinnedMesh
              name="tree_2"
              geometry={nodes.tree_2.geometry}
              material={materials.Branch}
              skeleton={nodes.tree_2.skeleton}
            />
            <skinnedMesh
              name="tree_3"
              geometry={nodes.tree_3.geometry}
              material={materials.Bark}
              skeleton={nodes.tree_3.skeleton}
            />
          </group>
          <primitive object={nodes.root} />
          <primitive object={nodes.neutral_bone} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tree.glb')
